generatorName: java
outputDir: samples/client/petstore/java/retrofit2-jackson
library: retrofit2-jackson
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-retrofit2-jackson
  hideGenerationTimestamp: "true"
